apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  slack-webhook: {{ .Values.secrets.slackWebhook | quote }}
  virustotal-api-key: {{ .Values.secrets.virustotalApiKey | quote }}
  abuseipdb-api-key: {{ .Values.secrets.abuseipdbApiKey | quote }}
  otx-api-key: {{ .Values.secrets.otxApiKey | quote }}
