"""
CyberNest Alert Model.

Pydantic v2 model representing a security alert generated by the correlation
engine when a detection rule matches one or more events.

Flow: Correlator -> Kafka cybernest.alerts -> Alert Manager -> PostgreSQL + ES.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator


class AlertSeverity(str, Enum):
    """Alert severity levels aligned with common SIEM conventions."""

    INFORMATIONAL = "informational"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertStatus(str, Enum):
    """Alert lifecycle states."""

    NEW = "new"
    ACKNOWLEDGED = "acknowledged"
    IN_PROGRESS = "in_progress"
    RESOLVED = "resolved"
    CLOSED = "closed"
    FALSE_POSITIVE = "false_positive"


class CyberNestAlert(BaseModel):
    """Full alert record for the CyberNest detection pipeline.

    Created by the correlator, persisted to PostgreSQL and Elasticsearch,
    displayed on the dashboard, and optionally escalated via SOAR playbooks.
    """

    model_config = {
        "populate_by_name": True,
        "from_attributes": True,
        "extra": "allow",
    }

    # --- Identity ----------------------------------------------------------
    alert_id: str = Field(
        default_factory=lambda: uuid4().hex,
        description="Unique alert identifier.",
    )
    rule_id: str = Field(
        default="",
        description="ID of the detection rule that fired.",
    )
    rule_name: str = Field(
        default="",
        description="Human-readable name of the detection rule.",
    )

    # --- Classification ----------------------------------------------------
    severity: AlertSeverity = Field(
        default=AlertSeverity.MEDIUM,
        description="Alert severity level.",
    )
    status: AlertStatus = Field(
        default=AlertStatus.NEW,
        description="Current lifecycle status.",
    )
    title: str = Field(
        default="",
        description="Short alert title shown in the UI.",
    )
    description: str = Field(
        default="",
        description="Detailed alert description / analyst notes.",
    )

    # --- Context -----------------------------------------------------------
    source_ip: Optional[str] = Field(
        None, description="Source IP address from the triggering event."
    )
    destination_ip: Optional[str] = Field(
        None, description="Destination IP address from the triggering event."
    )
    username: Optional[str] = Field(
        None, description="Username associated with the event."
    )
    hostname: Optional[str] = Field(
        None, description="Hostname where the event occurred."
    )

    # --- Evidence ----------------------------------------------------------
    raw_log: Optional[str] = Field(
        None, description="Original raw log line(s) that triggered the alert."
    )
    parsed_event: Optional[dict[str, Any]] = Field(
        None, description="Parsed ECS event dict snapshot."
    )
    event_ids: list[str] = Field(
        default_factory=list,
        description="IDs of correlated events that contributed to this alert.",
    )
    event_count: int = Field(
        default=1, ge=1, description="Number of events that matched the rule."
    )

    # --- MITRE ATT&CK mapping ----------------------------------------------
    mitre_tactic: Optional[str] = Field(
        None, description="Primary MITRE ATT&CK tactic ID (e.g. TA0001)."
    )
    mitre_technique: list[str] = Field(
        default_factory=list,
        description="List of MITRE ATT&CK technique IDs (e.g. T1059.001).",
    )

    # --- Risk scoring ------------------------------------------------------
    risk_score: float = Field(
        default=0.0,
        ge=0.0,
        le=100.0,
        description="Composite risk score (0-100).",
    )

    # --- Enrichment --------------------------------------------------------
    threat_intel: Optional[dict[str, Any]] = Field(
        None, description="Threat intelligence enrichment data."
    )
    geo_data: Optional[dict[str, Any]] = Field(
        None, description="GeoIP enrichment data."
    )
    asset_info: Optional[dict[str, Any]] = Field(
        None, description="Asset management enrichment data."
    )

    # --- Assignment --------------------------------------------------------
    assignee_id: Optional[str] = Field(
        None, description="User ID of the assigned analyst."
    )
    incident_id: Optional[str] = Field(
        None, description="Linked incident ID if escalated."
    )

    # --- Timestamps --------------------------------------------------------
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Alert creation timestamp (UTC).",
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Last update timestamp (UTC).",
    )
    acknowledged_at: Optional[datetime] = Field(
        None, description="When the alert was acknowledged by an analyst."
    )
    resolved_at: Optional[datetime] = Field(
        None, description="When the alert was resolved."
    )

    # --- Comments / audit trail --------------------------------------------
    comments: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Analyst comments. Each entry: {author, text, timestamp}.",
    )

    # --- Validators --------------------------------------------------------
    @field_validator("severity", mode="before")
    @classmethod
    def normalize_severity(cls, v: Any) -> Any:
        """Accept string severity values case-insensitively."""
        if isinstance(v, str):
            return v.lower()
        return v

    @field_validator("status", mode="before")
    @classmethod
    def normalize_status(cls, v: Any) -> Any:
        """Accept string status values case-insensitively."""
        if isinstance(v, str):
            return v.lower()
        return v

    @field_validator("mitre_technique", mode="before")
    @classmethod
    def ensure_technique_list(cls, v: Any) -> list[str]:
        """Accept a single technique string and wrap in list."""
        if v is None:
            return []
        if isinstance(v, str):
            return [v]
        return list(v)

    @field_validator("created_at", "updated_at", mode="before")
    @classmethod
    def parse_datetime_strings(cls, v: Any) -> Any:
        """Accept ISO format strings for datetime fields."""
        if isinstance(v, str) and v:
            return datetime.fromisoformat(v.replace("Z", "+00:00"))
        return v
