"""CyberNest — Alert data model for the detection pipeline."""

from __future__ import annotations
from datetime import datetime
from pydantic import BaseModel, Field


class CyberNestAlert(BaseModel):
    """Alert generated by the correlation engine when a rule matches.

    Flows: Correlator → Kafka cybernest.alerts → Alert Manager → PostgreSQL + ES.
    """
    id: str = ""
    alert_id: str = ""
    title: str = ""
    description: str = ""
    severity: str = "medium"
    level: int = 5
    status: str = "new"
    alert_type: str = "rule_match"

    # Rule context
    rule_id: str = ""
    rule_name: str = ""

    # Network context
    source_ip: str | None = None
    source_port: int | None = None
    destination_ip: str | None = None
    destination_port: int | None = None
    protocol: str | None = None

    # Host context
    hostname: str | None = None
    agent_id: str | None = None

    # User context
    username: str | None = None
    process_name: str | None = None

    # IOC
    ioc_type: str | None = None
    ioc_value: str | None = None

    # MITRE ATT&CK
    mitre_tactics: list[str] = Field(default_factory=list)
    mitre_techniques: list[str] = Field(default_factory=list)

    # Enrichment
    threat_intel: dict | None = None
    geo_data: dict | None = None
    asset_info: dict | None = None

    # Evidence
    raw_log: str | None = None
    event_ids: list[str] = Field(default_factory=list)
    event_count: int = 1
    parsed_event: dict | None = None

    # Assignment
    assignee_id: str | None = None
    incident_id: str | None = None

    # UEBA
    ueba_score: float | None = None

    # Timestamps
    created_at: str = ""
    acknowledged_at: str | None = None
    resolved_at: str | None = None
    ttd_ms: int | None = None
    ttr_ms: int | None = None

    # Comments
    comments: list[dict] = Field(default_factory=list)
